[versions]
algoutils = "0.4.0"

[libraries]
annotations = "org.jetbrains:annotations:23.0.0"
algoutils-student = { module = "org.tudalgo:algoutils-student", version.ref = "algoutils" }
algoutils-tutor = { module = "org.tudalgo:algoutils-tutor", version.ref = "algoutils" }
junit-core = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.1" }

[plugins]
style = { id = "org.sourcegrade.style", version = "2.1.0" }
jagr-gradle = { id = "org.sourcegrade.jagr-gradle", version = "0.6.2" }
